### ISSUE TITLE
确认SecondPage第二个饼图的表现形式

### ISSUE THREAD

**Issue by rickyyin98** [rickyyin98/Github-Times#7]
如果确定使用现有的表示形式，可以在评论中回复。

如果有更好的表示形式，可以直接给出。

**Comment by MeatbunBigking** [comment]
https://github.com/MeatbunBigking/GitHub-Times-New
新的饼图和代码更新在里面了

**Comment by cheerupyxolive** [comment]
> https://github.com/MeatbunBigking/GitHub-Times-New
> 新的饼图和代码更新在里面了

配色和形式都好看很多，可以使用。但确实这图只有两个数据，传递的信息不够有意义（文字里已有），不放也可。
